"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Banknote, ClipboardCheck, History, ShieldCheck } from "lucide-react";
import type { Locale } from "@/app/i18n";

const copy = {
  ar:{ title:"الصندوق والتدقيق النقدي", subtitle:"تسجيل المبيعات النقدية والإيداعات ومطابقتها دون حذف أو تعديل", cashier:"اسم المحاسب", amount:"المبلغ", reference:"مرجع الإيداع البنكي", note:"ملاحظة التدقيق", type:"نوع الحركة", deposit:"إيداع نقدي", withdrawal:"سحب موثق", adjustment:"تسوية موثقة", save:"تسجيل الحركة", saving:"جارٍ التسجيل", balance:"الرصيد المتوقع بالصندوق", sales:"المبيعات النقدية", deposits:"الإيداعات", audit:"سجل التدقيق", date:"التاريخ", movement:"الحركة", status:"موثقة", required:"أدخل اسم المحاسب والمبلغ ومرجع الإيداع", failed:"تعذر تسجيل الحركة", saved:"تم تسجيل الحركة بنجاح", sar:"ر.س", immutable:"السجل تراكمي؛ لا يمكن حذف أو تعديل حركة بعد تسجيلها."},
  en:{ title:"Cash register and audit", subtitle:"Record cash sales and deposits with an immutable audit trail", cashier:"Cashier name", amount:"Amount", reference:"Bank deposit reference", note:"Audit note", type:"Movement type", deposit:"Cash deposit", withdrawal:"Recorded withdrawal", adjustment:"Recorded adjustment", save:"Record movement", saving:"Recording", balance:"Expected cash balance", sales:"Cash sales", deposits:"Deposits", audit:"Audit log", date:"Date", movement:"Movement", status:"Recorded", required:"Enter cashier name, amount, and deposit reference", failed:"Movement could not be recorded", saved:"Movement recorded", sar:"SAR", immutable:"This is an append-only audit trail; recorded movements cannot be deleted or edited."},
} as const;

type Item = { id:string; movement_type:string; amount_minor:number; cashier_name:string; deposit_reference:string; note:string; created_at:string };
export function CashControlView({ locale }:{ locale:Locale }) {
  const t=copy[locale]; const [cashierName,setCashierName]=useState(""); const [amount,setAmount]=useState(""); const [reference,setReference]=useState(""); const [note,setNote]=useState(""); const [movementType,setMovementType]=useState("deposit"); const [status,setStatus]=useState<"idle"|"saving"|"saved"|"error"|"invalid">("idle"); const [data,setData]=useState<{balanceMinor:number;salesMinor:number;purchasesMinor:number;depositsMinor:number;items:Item[]}>({balanceMinor:0,salesMinor:0,purchasesMinor:0,depositsMinor:0,items:[]});
  const refresh=()=>fetch("/api/cash",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>{});
  useEffect(()=>{void refresh();},[]);
  const submit=async()=>{if(!cashierName.trim()||!Number(amount)||Number(amount)<=0||(movementType==="deposit"&&!reference.trim())) return setStatus("invalid"); setStatus("saving"); try{const r=await fetch("/api/cash",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cashierName,amount:Number(amount),depositReference:reference,note,movementType})}); if(!r.ok) throw new Error(); setStatus("saved"); setAmount("");setReference("");setNote("");void refresh();}catch{setStatus("error");}};
  const money=(minor:number)=>`${(Number(minor||0)/100).toFixed(2)} ${t.sar}`;
  return <section className="cash-workspace" aria-labelledby="cash-title"><div className="cash-toolbar"><div><span><Banknote size={17}/>{t.audit}</span><h2 id="cash-title">{t.title}</h2><p>{t.subtitle}</p></div><Badge><ShieldCheck size={14}/>{t.immutable}</Badge></div><div className="cash-metrics"><article><span>{t.balance}</span><strong>{money(data.balanceMinor)}</strong></article><article><span>{t.sales}</span><strong>{money(data.salesMinor)}</strong></article><article><span>{locale==="ar"?"المشتريات النقدية":"Cash purchases"}</span><strong>{money(data.purchasesMinor)}</strong></article><article><span>{t.deposits}</span><strong>{money(data.depositsMinor)}</strong></article></div><div className="cash-layout"><article className="cash-form"><div className="cash-form-grid"><label>{t.cashier}<Input value={cashierName} onChange={e=>setCashierName(e.target.value)}/></label><label>{t.type}<Select value={movementType} onValueChange={setMovementType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="deposit">{t.deposit}</SelectItem><SelectItem value="withdrawal">{t.withdrawal}</SelectItem><SelectItem value="adjustment">{t.adjustment}</SelectItem></SelectContent></Select></label><label>{t.amount}<Input dir="ltr" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{t.reference}<Input dir="ltr" value={reference} onChange={e=>setReference(e.target.value)}/></label></div><label>{t.note}<Input value={note} onChange={e=>setNote(e.target.value)}/></label>{status!=="idle"&&<p className={`cash-message ${status}`}>{status==="saved"?t.saved:status==="invalid"?t.required:t.failed}</p>}<Button onClick={submit} disabled={status==="saving"}><ClipboardCheck size={16}/>{status==="saving"?t.saving:t.save}</Button></article><article className="cash-audit"><h3><History size={17}/>{t.audit}</h3>{data.items.length===0?<p className="cash-empty">—</p>:data.items.map(item=><div className="cash-row" key={item.id}><div><strong>{item.movement_type==="cash_sale"?t.sales:item.movement_type==="cash_purchase"?(locale==="ar"?"مشتريات نقدية":"Cash purchase"):item.movement_type==="deposit"?t.deposit:item.movement_type==="withdrawal"?t.withdrawal:t.adjustment}</strong><small>{item.cashier_name} · {new Date(item.created_at).toLocaleString(locale==="ar"?"ar-SA":"en-GB")}</small></div><b dir="ltr">{money(item.amount_minor)}</b><Badge>{t.status}</Badge></div>)}</article></div></section>;
}
